import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  {
    name: "Laptop ThinkPad E14",
    description: "Laptop empresarial liviana con buen balance entre rendimiento y portabilidad.",
    price: 3200000,
    brand: "Lenovo",
    category: "laptops",
    specs: { ram: "16GB", procesador: "i7", almacenamiento: "512GB SSD" },
    stock: 15,
    imageUrl: "https://placehold.co/400x400?text=ThinkPad+E14",
  },
  {
    name: "Laptop MacBook Air M2",
    description: "Ultraliviana, gran autonomía de batería, ideal para trabajo diario.",
    price: 5800000,
    brand: "Apple",
    category: "laptops",
    specs: { ram: "8GB", procesador: "Apple M2", almacenamiento: "256GB SSD" },
    stock: 8,
    imageUrl: "https://placehold.co/400x400?text=MacBook+Air",
  },
  {
    name: "Laptop Pavilion 15",
    description: "Laptop de uso general para estudio y oficina.",
    price: 2100000,
    brand: "HP",
    category: "laptops",
    specs: { ram: "8GB", procesador: "i5", almacenamiento: "256GB SSD" },
    stock: 20,
    imageUrl: "https://placehold.co/400x400?text=Pavilion+15",
  },
  {
    name: "Laptop Gamer ROG Strix",
    description: "Laptop gamer de alto rendimiento con tarjeta gráfica dedicada.",
    price: 7500000,
    brand: "Asus",
    category: "laptops",
    specs: { ram: "32GB", procesador: "i9", gpu: "RTX 4070" },
    stock: 5,
    imageUrl: "https://placehold.co/400x400?text=ROG+Strix",
  },
  {
    name: "iPhone 15",
    description: "Smartphone Apple con cámara doble y chip A16.",
    price: 4200000,
    brand: "Apple",
    category: "celulares",
    specs: { ram: "6GB", almacenamiento: "128GB", pantalla: "6.1 pulgadas" },
    stock: 12,
    imageUrl: "https://placehold.co/400x400?text=iPhone+15",
  },
  {
    name: "Samsung Galaxy S24",
    description: "Smartphone Android con pantalla AMOLED y cámara de 50MP.",
    price: 3800000,
    brand: "Samsung",
    category: "celulares",
    specs: { ram: "8GB", almacenamiento: "256GB", pantalla: "6.2 pulgadas" },
    stock: 18,
    imageUrl: "https://placehold.co/400x400?text=Galaxy+S24",
  },
  {
    name: "Xiaomi Redmi Note 13",
    description: "Smartphone gama media con excelente relación precio-rendimiento.",
    price: 950000,
    brand: "Xiaomi",
    category: "celulares",
    specs: { ram: "6GB", almacenamiento: "128GB", pantalla: "6.67 pulgadas" },
    stock: 30,
    imageUrl: "https://placehold.co/400x400?text=Redmi+Note+13",
  },
  {
    name: "Motorola Edge 40",
    description: "Smartphone con diseño delgado y carga rápida de 68W.",
    price: 1600000,
    brand: "Motorola",
    category: "celulares",
    specs: { ram: "8GB", almacenamiento: "256GB", pantalla: "6.55 pulgadas" },
    stock: 14,
    imageUrl: "https://placehold.co/400x400?text=Edge+40",
  },
  {
    name: "Audífonos WH-1000XM5",
    description: "Audífonos inalámbricos con cancelación de ruido líder en la industria.",
    price: 1350000,
    brand: "Sony",
    category: "audio",
    specs: { tipo: "over-ear", bateria: "30 horas", cancelacionRuido: true },
    stock: 22,
    imageUrl: "https://placehold.co/400x400?text=WH-1000XM5",
  },
  {
    name: "AirPods Pro 2",
    description: "Audífonos in-ear con cancelación activa de ruido y estuche MagSafe.",
    price: 980000,
    brand: "Apple",
    category: "audio",
    specs: { tipo: "in-ear", bateria: "6 horas", cancelacionRuido: true },
    stock: 25,
    imageUrl: "https://placehold.co/400x400?text=AirPods+Pro+2",
  },
  {
    name: "Audífonos JBL Tune 510BT",
    description: "Audífonos inalámbricos económicos con buen sonido para uso diario.",
    price: 180000,
    brand: "JBL",
    category: "audio",
    specs: { tipo: "on-ear", bateria: "40 horas", cancelacionRuido: false },
    stock: 40,
    imageUrl: "https://placehold.co/400x400?text=JBL+Tune+510BT",
  },
  {
    name: "Monitor UltraGear 27'' 144Hz",
    description: "Monitor gamer Full HD con alta tasa de refresco.",
    price: 1100000,
    brand: "LG",
    category: "monitores",
    specs: { tamano: "27 pulgadas", resolucion: "1920x1080", refresco: "144Hz" },
    stock: 16,
    imageUrl: "https://placehold.co/400x400?text=UltraGear+27",
  },
  {
    name: "Monitor Odyssey G5 32''",
    description: "Monitor curvo QHD ideal para gaming y productividad.",
    price: 1650000,
    brand: "Samsung",
    category: "monitores",
    specs: { tamano: "32 pulgadas", resolucion: "2560x1440", refresco: "165Hz" },
    stock: 10,
    imageUrl: "https://placehold.co/400x400?text=Odyssey+G5",
  },
  {
    name: "Monitor ProArt 24''",
    description: "Monitor con precisión de color para diseño gráfico.",
    price: 1400000,
    brand: "Asus",
    category: "monitores",
    specs: { tamano: "24 pulgadas", resolucion: "1920x1200", refresco: "60Hz" },
    stock: 9,
    imageUrl: "https://placehold.co/400x400?text=ProArt+24",
  },
  {
    name: "Teclado Mecánico K95 RGB",
    description: "Teclado mecánico gamer con switches Cherry MX y retroiluminación RGB.",
    price: 650000,
    brand: "Corsair",
    category: "perifericos",
    specs: { switches: "Cherry MX Red", conexion: "USB", retroiluminacion: "RGB" },
    stock: 20,
    imageUrl: "https://placehold.co/400x400?text=K95+RGB",
  },
  {
    name: "Mouse MX Master 3S",
    description: "Mouse inalámbrico ergonómico de alta precisión para productividad.",
    price: 480000,
    brand: "Logitech",
    category: "perifericos",
    specs: { conexion: "Bluetooth/USB", dpi: "8000", ergonomico: true },
    stock: 28,
    imageUrl: "https://placehold.co/400x400?text=MX+Master+3S",
  },
  {
    name: "Mouse Gamer DeathAdder V3",
    description: "Mouse gamer ultraliviano con sensor óptico de alta precisión.",
    price: 320000,
    brand: "Razer",
    category: "perifericos",
    specs: { conexion: "USB", dpi: "30000", ergonomico: false },
    stock: 24,
    imageUrl: "https://placehold.co/400x400?text=DeathAdder+V3",
  },
  {
    name: "Tablet iPad 10ma generación",
    description: "Tablet versátil para estudio, entretenimiento y productividad ligera.",
    price: 2400000,
    brand: "Apple",
    category: "tablets",
    specs: { ram: "4GB", almacenamiento: "64GB", pantalla: "10.9 pulgadas" },
    stock: 13,
    imageUrl: "https://placehold.co/400x400?text=iPad+10",
  },
  {
    name: "Tablet Galaxy Tab S9",
    description: "Tablet Android premium con pantalla AMOLED y S Pen incluido.",
    price: 3100000,
    brand: "Samsung",
    category: "tablets",
    specs: { ram: "8GB", almacenamiento: "128GB", pantalla: "11 pulgadas" },
    stock: 7,
    imageUrl: "https://placehold.co/400x400?text=Galaxy+Tab+S9",
  },
  {
    name: "SSD NVMe 1TB",
    description: "Disco de estado sólido NVMe de alta velocidad para actualizar tu equipo.",
    price: 420000,
    brand: "Samsung",
    category: "componentes",
    specs: { capacidad: "1TB", interfaz: "NVMe M.2", velocidadLectura: "3500MB/s" },
    stock: 35,
    imageUrl: "https://placehold.co/400x400?text=SSD+NVMe+1TB",
  },
  {
    name: "Memoria RAM 16GB DDR4",
    description: "Kit de memoria RAM DDR4 para mejorar el rendimiento multitarea.",
    price: 280000,
    brand: "Kingston",
    category: "componentes",
    specs: { capacidad: "16GB", tipo: "DDR4", velocidad: "3200MHz" },
    stock: 45,
    imageUrl: "https://placehold.co/400x400?text=RAM+16GB",
  },
  {
    name: "Smartwatch Watch Series 9",
    description: "Reloj inteligente con monitoreo de salud y notificaciones.",
    price: 1900000,
    brand: "Apple",
    category: "wearables",
    specs: { pantalla: "AMOLED", bateria: "18 horas", resistenciaAgua: true },
    stock: 11,
    imageUrl: "https://placehold.co/400x400?text=Watch+Series+9",
  },
  {
    name: "Smartwatch Galaxy Watch 6",
    description: "Reloj inteligente Android con seguimiento de actividad física.",
    price: 1300000,
    brand: "Samsung",
    category: "wearables",
    specs: { pantalla: "AMOLED", bateria: "40 horas", resistenciaAgua: true },
    stock: 15,
    imageUrl: "https://placehold.co/400x400?text=Galaxy+Watch+6",
  },
];

async function main() {
  for (const product of products) {
    await prisma.product.create({ data: product });
  }
  console.log(`Seed completado: ${products.length} productos creados.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
